
FROM mcr.microsoft.com/windows/servercore:ltsc2022

ENV CompanyName="Grid Protection Alliance" \
    CompanyAcronym="GPA" \
    ConnectionString="Data Source=localhost; Initial Catalog=openXDA;" 


ADD ./SystemCenterSetup.msi c:/setup/
RUN C:/setup/SystemCenterSetup.msi INTEGRATEDSECURITY=NO COMPANYNAME=env(USER:CompanyName) COMPANYACRONYM=env(USER:CompanyAcronym) DEFAULTCONNECTIONSTRING=env(USER:ConnectionString)  /q /l*v log.log


COPY ./startDocker.ps1 c:/scripts/

EXPOSE 8987/tcp
CMD ["powershell", "C:/scripts/startDocker.ps1"]